export const UPDATE_LOGGED_IN_DETAILS = "UPDATE_LOGGED_IN_DETAILS"

export const CHANGE_CURRENT_EXPENSE = "CHANGE_CURRENT_EXPENSE";

export const CHANGE_SELECTED_DAY = "CHANGE_SELECTED_DAY";

export const TOGGLE_BACKDROP = "TOGGLE_BACKDROP";

export const TOGGLE_MODAL = "TOGGLE_MODAL";